name: sedo_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  build_runner: ^2.4.9
  devangels_show_debug_paint: ^0.0.4
  flick_video_player: ^0.8.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_polyline_points: ^2.0.0
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  http: ^1.2.1
  intl_phone_field: ^3.0.0
  json_annotation: ^4.8.1
  kkiapay_flutter_sdk: ^1.3.2
  location: ^6.0.1
  open_location_code: ^1.0.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  stacked: ^3.4.0
  stacked_hooks: ^0.2.4
  stacked_services: ^1.1.0
  uuid: ^4.4.0
  video_player: ^2.8.6

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/launch.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/launch.png
    - assets/time.png
    - assets/History.svg
    - assets/HistoryColor.svg
    - assets/map_round.svg
    - assets/Map_color.png
    - assets/Map_w_color.png
    - assets/cercletime.svg
    - assets/user_speak.svg
    - assets/user_speak_color.svg
    - assets/map_point_wave.svg
    - assets/arrow-right.svg
    - assets/profile-img.svg
    - assets/user.svg
    - assets/not-bacgkound-delivery.png
    - assets/left-con.svg
    - assets/delete-icon.svg
    - assets/active-icon.png
    - assets/inactive-icon.png
    - assets/blackpen.svg
    - assets/pencil.png
    - assets/pen2.svg
