import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:uuid/uuid.dart';

String userId = "";
String token = "";
String tokenSave = "";
String userName = "";
String userSurname = "";
String userEmail = "";
String userPhone = "";
const headers = {'Content-Type': 'application/json'};
const String googleApiKey = "AIzaSyAT15yqrfAE4IcwB-Q45GA-j_mYQPafTIY";
String kkiapayApiKey = "3928a210406a11ef8cc77f54de9d35c7";
late GoogleMapController mapController;
LatLng currentLocation = const LatLng(45.521563, -122.677433);
String deliveryTime = "";
List<dynamic> bankCard = [1, 2, 3, 4];
List<String> numInfo = [];
var uuid = const Uuid();
String? sessionToken;
String? placeId;
List<dynamic> placeList = [];
String recoveryName = "";
String recoveryPhone = "";
String coursesTitle = "";
String coursesDescription = "";
double recoveryLongitude = 0;
double recoveryLatitude = 0;
String destinationName = "";
String destinationPhone = "";
double destinationLongitude = 0;
double destinationLatitude = 0;
bool isDeliveryExpress = false;
String duration = "";
String region = "";
double distance = 0;
String shipPrice = "";