import 'package:uuid/uuid.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

String userId = "";
String token = "";
String tokenSave = "";
String userName = "";
String userSurname = "";
String userEmail = "";
String userPhone = "";
const headers = {'Content-Type': 'application/json'};
const String googleApiKey = "AIzaSyAT15yqrfAE4IcwB-Q45GA-j_mYQPafTIY";
const String kkiapayApiKey = "pk_5024b71b56965681cdd4439788aa3e45591a429f0e391161899a27ce1f8ff1f9";
late GoogleMapController mapController;
LatLng currentLocation = const LatLng(0, 0);
String deliveryTime = "";
List<dynamic> bankCard = [1, 2, 3, 4];
List<String> numInfo = [];
var uuid = const Uuid();
String? sessionToken;
String? placeId;
List<dynamic> placeList = [];
String recoveryName = "";
String recoveryPhone = "";
String coursesTitle = "";
String coursesDescription = "";
double recoveryLongitude = 0;
double recoveryLatitude = 0;
String destinationName = "";
String destinationPhone = "";
double destinationLongitude = 0;
double destinationLatitude = 0;
bool isDeliveryExpress = false;
String duration = "";
String region = "";
double distance = 0;
String shipPrice = "";
bool onTapMap = false;
String shipId = "";
String coursesStatus = "";

